name = "recept-api"
main = "worker.js"
compatibility_date = "2026-07-06"
routes = [{ pattern = "recept-api.buildapp.se", custom_domain = true }]

[[d1_databases]]
binding = "DB"
database_name = "recept"
database_id = "519f743c-9c5e-48c0-930b-c615ada71f0c"
